### ISSUE TITLE
Vanilla JS Implementation

### ISSUE THREAD

**Issue by Konrud** [makeup-js/makeup-keyboard-trap#1]
When I first saw your implementation for keyboard trap using JQuery I was so excited.
 I was waiting for vanilla JS implementation too long so I've implemented it myself a month ago. 
Now I've found you did this vanilla JS version and I'm very pleased to see that's my version is very similar to what you've done, I still don't understand why you need outer traps, though.
 Thank you very much for what you've done and for the inspiration that you gave me with your JQuery version of this plugin.

my vanilla js implementation:
https://codepen.io/Konrud/pen/RgjxOL

**Comment by ianmcburnie** [comment]
You are more than welcome, thank you for the kind words and I'm glad you've found it useful. Oh, and sorry for the long wait!

In terms of the outer traps, it's a bit of an edge case. Imagine if a user switches from keyboard to mouse and clicks on something outside the trapped area. If they then again switch back to keyboard and tab through the page, the outer trap ensures focus gets moved to the first element inside the trap. If it wasn't there, the inner trap would be hit and it would move focus to the last element in the trapped area, which would be odd. Like I say, an edge case, and maybe not strictly necessary, especially in the case of a modal dialog with mask that prevents users from clicking outside trapped area.

Hope that makes sense! If you have any ideas for improvements, be sure to let me know.
