### ISSUE TITLE
Add way to reset focus elements

### ISSUE THREAD

**Issue by sendlo** [makeup-js/makeup-keyboard-trap#7]
If the content is modified the focus elements may not be valid targets anymore.  I can resubmit the trap, but that has the extra overhead of re-adding the DOM elements.  It would be good if we could just tell the plugin to reselect the first and last focus elements.

**Comment by ianmcburnie** [comment]
Nice idea. Will work on it.

**Comment by ianmcburnie** [comment]
I added a refresh method. Please update and let me know if it works for your case.

https://github.com/makeup-js/makeup-keyboard-trap/commit/5e53190d64ad5a4a351e96b0a7c40e6f7ac52908#diff-1fdf421c05c1140f6d71444ea2b27638R104

The only danger I see in this method, as opposed to resubmitting the trap, is that it does not guarantee
 the inner traps are still in first and last position, and so things could get a little screwy if not...
